load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
    name = "test1",
    srcs = [
        "test.cpp",
    ],
    deps = [
        "@baidu_apollo//modules/map/hdmap:hdmap",
        # "@baidu_apollo//modules/routing:apollo_routing",
    ],
)